In [6]:
%matplotlib inline
import numpy as np
import pandas as pd

In [2]:
# a is the one hot encoding input vector of RNN
# p is the output probability vector of RNN

In [56]:
def prediction(a,p):
    for i in range(np.size(a)):
        if a[i]>=1:
            p[i]=0
    return p

In [65]:
def prediction2(a,p):
     return(np.where(a==0,p,0))
    
   

In [74]:
def prediction3(a,p):
    return(np.array((a==0)*p))

In [ ]:
user_movie = pd.read_csv("user_movies_1hot.csv", sep=",")

In [72]:
mat=user_movie.groupby('userID').sum()
mat

101 Dalmatians   13th Warrior, The   2 Days in the Valley   \
userID                                                               
1                     0                   0                      0   
2                     0                   0                      0   
12                    0                   0                      1   
15                    0                   1                      0   
17                    0                   0                      0   
18                    2                   1                      0   
19                    0                   0                      0   

        20,000 Leagues Under the Sea   2001: A Space Odyssey   2010   \
userID                                                                 
1                                   0                       0      0   
2                                   0                       0      0   
12                                  0                       0      0   
15                                  0                       0      0   
17                                  1                       1      1   
18                                  0                       0      0   
19                                  0                       0      0   

        28 Days   3 Ninjas: High Noon On Mega Mountain   54   Abyss, The   \
userID                                                                      
1              0                                      0    0            0   
2              0                                      0    0            0   
12             0                                      0    0            0   
15             1                                      0    1            0   
17             0                                      0    0            1   
18             0                                      1    0            0   
19             0                                      0    0            0   

          ...      Wings of the Dove, The   Wizard of Oz, The   \
userID    ...                                                    
1         ...                            0                   1   
2         ...                            0                   0   
12        ...                            0                   1   
15        ...                            0                   0   
17        ...                            0                   0   
18        ...                            1                   1   
19        ...                            0                   1   

        X-Files: Fight the Future, The   X-Men   Yojimbo   You've Got Mail   \
userID                                                                        
1                                     0       0         0                 0   
2                                     0       0         1                 0   
12                                    0       0         0                 0   
15                                    1       0         0                 1   
17                                    1       1         0                 0   
18                                    0       1         0                 0   
19                                    1       1         0                 0   

        Young Guns   Young Guns II   Young Sherlock Holmes   eXistenZ   
userID                                                                  
1                 0               0                       0          0  
2                 0               0                       0          0  
12                0               0                       0          0  
15                0               0                       0          0  
17                0               0                       0          1  
18                1               1                       1          0  
19                0               0                       0          0  

[7 rows x 664 columns]

In [85]:
mat.shape

(7, 664)

In [87]:
col= mat.columns.size


664

In [88]:
p=np.random.rand(col)
p

array([  1.66555853e-02,   3.00601912e-01,   9.92161912e-01,
         9.78829531e-01,   3.75731737e-01,   5.70212595e-01,
         4.88473146e-01,   4.43580757e-01,   9.11265396e-01,
         8.85014418e-01,   5.77594996e-01,   1.87687605e-01,
         5.92910526e-01,   1.39377345e-01,   9.53451269e-01,
         1.98966507e-02,   7.68869904e-01,   6.31055629e-01,
         9.65514545e-01,   7.31954795e-01,   2.23068634e-01,
         1.74554036e-01,   7.45945722e-01,   8.73183155e-02,
         6.68085648e-01,   4.43228866e-01,   9.06983552e-01,
         2.57936886e-01,   1.13924239e-01,   8.27754313e-02,
         8.96812097e-01,   3.46833368e-01,   2.76319299e-01,
         2.14775523e-01,   2.50085674e-01,   7.93032938e-01,
         7.96622396e-01,   3.17855466e-01,   9.76578740e-01,
         8.76045488e-01,   2.49346336e-01,   2.78900265e-01,
         2.99564320e-01,   3.81228381e-02,   9.61913950e-01,
         2.56845145e-01,   1.56342820e-01,   1.22085769e-01,
         3.96171003e-01,

In [83]:
user=1

In [91]:
result=prediction2(mat.iloc[user,:],p)

In [79]:
prediction3(mat1.iloc[user,:],p)

array([0, 1, 0, 1])

In [80]:
prediction(mat1.iloc[user,:],p)

[0, 1, 0, 1]

In [97]:
top=3
#np.argmax(result)
result.argsort()[-top:]

array([192, 505, 639])

In [93]:
mat.columns[639]

'War, The '